name: "Coverage Deploy to Codacy"

on: push

jobs:
  test_deploy:
    runs-on: ubuntu-latest
        
    steps:
    - uses: actions/checkout@v2


    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
        
    - name: Setup conda
      uses: s-weigand/setup-conda@v1
      with:
        update-conda: true
        python-version: ${{ matrix.python-version }}
        conda-channels: anaconda, conda-forge

    - name: Install Python dependencies
      run: |
        conda install --yes pythonocc-core=7.4.0 numpy scipy matplotlib
    
    - name: Test with pytest
      env:
        CODACY_API_TOKEN: ${{ secrets.CODACY_API_TOKEN }}
      shell: bash
      run: |
        python3 -m pytest --cov-report term --cov-report xml:cobertura.xml --cov=bladex
        curl -s https://coverage.codacy.com/get.sh -o CodacyCoverageReporter.sh
        chmod +x CodacyCoverageReporter.sh
        ./CodacyCoverageReporter.sh report -r cobertura.xml  -t $CODACY_API_TOKEN
