name: "Testing Pull Request"

on:
  pull_request:
    branches:
      - "master"


jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest]
        python-version: [3.8, 3.7]
        
    steps:
    - uses: actions/checkout@v2


    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
      
    - name: Setup conda
        uses: s-weigand/setup-conda@v1
        with:
          update-conda: true
          python-version: ${{ matrix.python-version }}
          conda-channels: anaconda, conda-forge

    - name: Install Python dependencies
      run: |
        conda install --yes pythonocc-core=7.4.0 numpy scipy matplotlib
    
    - name: Test with pytest
      run: |
        python3 -m pytest
